package au.edu.unsw.soacourse.gnafaddressservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-01T16:58:06.134+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "GNAFAddressService", 
                  wsdlLocation = "file:/F:/Downloads-D-Backup/Semester_2_2016/EclipseWorkspace/GNAFAddressingService/src/main/resources/wsdl/GNAFService.wsdl",
                  targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au") 
public class GNAFAddressService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gnafaddressservice.soacourse.unsw.edu.au", "GNAFAddressService");
    public final static QName GNAFAddressServiceSOAP = new QName("http://gnafaddressservice.soacourse.unsw.edu.au", "GNAFAddressServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/Downloads-D-Backup/Semester_2_2016/EclipseWorkspace/GNAFAddressingService/src/main/resources/wsdl/GNAFService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GNAFAddressService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/Downloads-D-Backup/Semester_2_2016/EclipseWorkspace/GNAFAddressingService/src/main/resources/wsdl/GNAFService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GNAFAddressService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GNAFAddressService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GNAFAddressService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GNAFAddressService
     */
    @WebEndpoint(name = "GNAFAddressServiceSOAP")
    public GNAFAddressService getGNAFAddressServiceSOAP() {
        return super.getPort(GNAFAddressServiceSOAP, GNAFAddressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GNAFAddressService
     */
    @WebEndpoint(name = "GNAFAddressServiceSOAP")
    public GNAFAddressService getGNAFAddressServiceSOAP(WebServiceFeature... features) {
        return super.getPort(GNAFAddressServiceSOAP, GNAFAddressService.class, features);
    }

}
