package au.edu.unsw.soacourse.gnafaddressservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-01T16:58:06.120+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au", name = "GNAFAddressService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GNAFAddressService {

    @WebResult(name = "similarAddressesInFileResponse", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://gnafaddressservice.soacourse.unsw.edu.au/similarAddressesInFile")
    public SimilarAddressesInFileResponse similarAddressesInFile(
        @WebParam(partName = "parameters", name = "similarAddressesInFileRequest", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au")
        SimilarAddressesInFileRequest parameters
    ) throws SimilarAddressesInFileFaultMsg;

    @WebResult(name = "addressExistsInFileResponse", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://gnafaddressservice.soacourse.unsw.edu.au/addressExistsInFile")
    public AddressExistsInFileResponse addressExistsInFile(
        @WebParam(partName = "parameters", name = "addressExistsInFileRequest", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au")
        AddressExistsInFileRequest parameters
    ) throws AddressExistsInFileFaultMsg;

    @WebResult(name = "returnPostcodeInfoResponse", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://gnafaddressservice.soacourse.unsw.edu.au/returnPostcodeInfo")
    public ReturnPostcodeInfoResponse returnPostcodeInfo(
        @WebParam(partName = "parameters", name = "returnPostcodeInfoRequest", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au")
        ReturnPostcodeInfoRequest parameters
    ) throws ReturnPostcodeInfoFaultMsg;
}
