
package au.edu.unsw.soacourse.gnafaddressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-01T16:58:06.106+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "returnPostcodeInfoFault", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au")
public class ReturnPostcodeInfoFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType returnPostcodeInfoFault;

    public ReturnPostcodeInfoFaultMsg() {
        super();
    }
    
    public ReturnPostcodeInfoFaultMsg(String message) {
        super(message);
    }
    
    public ReturnPostcodeInfoFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ReturnPostcodeInfoFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType returnPostcodeInfoFault) {
        super(message);
        this.returnPostcodeInfoFault = returnPostcodeInfoFault;
    }

    public ReturnPostcodeInfoFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType returnPostcodeInfoFault, Throwable cause) {
        super(message, cause);
        this.returnPostcodeInfoFault = returnPostcodeInfoFault;
    }

    public au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType getFaultInfo() {
        return this.returnPostcodeInfoFault;
    }
}
