
package au.edu.unsw.soacourse.gnafaddressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-01T16:58:06.058+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "similarAddressesInFileFault", targetNamespace = "http://gnafaddressservice.soacourse.unsw.edu.au")
public class SimilarAddressesInFileFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType similarAddressesInFileFault;

    public SimilarAddressesInFileFaultMsg() {
        super();
    }
    
    public SimilarAddressesInFileFaultMsg(String message) {
        super(message);
    }
    
    public SimilarAddressesInFileFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SimilarAddressesInFileFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType similarAddressesInFileFault) {
        super(message);
        this.similarAddressesInFileFault = similarAddressesInFileFault;
    }

    public SimilarAddressesInFileFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType similarAddressesInFileFault, Throwable cause) {
        super(message, cause);
        this.similarAddressesInFileFault = similarAddressesInFileFault;
    }

    public au.edu.unsw.soacourse.gnafaddressservice.ServiceFaultType getFaultInfo() {
        return this.similarAddressesInFileFault;
    }
}
